# -*- coding: utf-8 -*-
"""HFLP_SCORES

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10VCUXRwYORH1rBO_E71Mv_LfEni1R3JK

# HFLP Scores
"""

antisemitism_test_original = [
{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'sentiment', 'score_1': 0.37670222200402464, 'score_2': -0.005299272610730026, 'score_3': -0.1005426408747933, 'score4': -0.09656219631595123},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'sentiment', 'score_1': 2.119377859966723, 'score_2': 0.1430430297007514, 'score_3': 0.4086986026541192, 'score4': 0.34027764551077605},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'sentiment', 'score_1': 1.5636696729757658, 'score_2': -0.8413002471351207, 'score_3': 0.19445380632826673, 'score4': 0.9159093861067269},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'sentiment', 'score_1': 0.9573937381168157, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'sentiment', 'score_1': 2.086692426010238, 'score_2': -1.9864471852427699, 'score_3': -0.6126513787372713, 'score4': 1.1433849792296389},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'sentiment', 'score_1': 2.3385925723215295, 'score_2': -2.8658585205066323, 'score_3': 0.5659282063325999, 'score4': 3.4722871826079995},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'sentiment', 'score_1': 2.236918679757371, 'score_2': -2.670563518100511, 'score_3': 0.05180901755172614, 'score4': 2.2984952329388797},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'sentiment', 'score_1': 2.574988097947276, 'score_2': -1.3147674196303807, 'score_3': 1.1083220722663298, 'score4': 3.07698986247166},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'sentiment', 'score_1': 1.5959697430745707, 'score_2': -1.6189875255172632, 'score_3': 0.06037460221312991, 'score4': 2.1335998636097515},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'patriotic', 'score_1': 0.6264663422414063, 'score_2': -0.5503061558472059, 'score_3': 0.04975521922434832, 'score4': 0.45985352756975634},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'patriotic', 'score_1': 0.4497006269249871, 'score_2': -0.12789222918112547, 'score_3': -1.4964799987174373, 'score4': -1.5851977431894526},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'patriotic', 'score_1': 2.4354922664115697, 'score_2': -0.5588773459025083, 'score_3': 0.56450812682738, 'score4': 1.0104171532851058},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'patriotic', 'score_1': 0, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'patriotic', 'score_1': 1.753005027837147, 'score_2': -2.708172978162502, 'score_3': -0.7730086712669643, 'score4': 1.5412882069041958},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'patriotic', 'score_1': 1.3268614669166483, 'score_2': -1.4680344736325102, 'score_3': -0.44506543486795186, 'score4': 0.9290309570683057},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'patriotic', 'score_1': 0.7893871560056842, 'score_2': -2.9189534484681423, 'score_3': -1.9264151334344242, 'score4': 0.835193818333426},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'patriotic', 'score_1': -0.2952483992358144, 'score_2': -1.8632523419804898, 'score_3': -1.7657457790593678, 'score4': -0.1344136469554441},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'patriotic', 'score_1': 2.1691813528633865, 'score_2': -1.0358880307462626, 'score_3': -0.08109223331008768, 'score4': 1.1053033364089166},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'economic', 'score_1': 0.25808692851993387, 'score_2': -0.9969401079552502, 'score_3': -0.14102396142766274, 'score4': 0.5269990141142932},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'economic', 'score_1': 2.4045477806644846, 'score_2': 0.21703774279927615, 'score_3': 0.7541211087508518, 'score4': 0.6731483926035725},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'economic', 'score_1': 2.1871990417387956, 'score_2': -0.20903883025626185, 'score_3': 1.1342840005853423, 'score4': 1.124279714273823},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'economic', 'score_1': -0.46809572931896015, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'economic', 'score_1': 0.952699900071511, 'score_2': -2.5429698233556586, 'score_3': -1.4216260464370758, 'score4': 0.6351249453304479},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'economic', 'score_1': 0.6376729885777802, 'score_2': -1.6263416554655998, 'score_3': -1.7988125271078437, 'score4': 0.2610185871831942},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'economic', 'score_1': 0.9453730577679547, 'score_2': -2.7986907330200874, 'score_3': -1.5368854429673147, 'score4': 1.0594492795486818},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'economic', 'score_1': 0.9658203967373897, 'score_2': -1.8959831782543688, 'score_3': -0.9763044716408937, 'score4': 1.1790498251067023},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'economic', 'score_1': 1.3899392742952357, 'score_2': -0.2338856368493809, 'score_3': -0.9922476067712904, 'score4': -0.5293944899257207},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'conspiratorial', 'score_1': 0.25383880123793107, 'score_2': -0.3493278664899513, 'score_3': 0.0768535463192094, 'score4': 0.3031259270628789},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'conspiratorial', 'score_1': 0.3546223104304719, 'score_2': 0.2132336007549482, 'score_3': -1.2097626824637222, 'score4': -1.5810862970769777},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'conspiratorial', 'score_1': 2.3923101914527587, 'score_2': -0.633825209432788, 'score_3': 0.9771798867481873, 'score4': 1.4709552134881954},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'conspiratorial', 'score_1': -1.8344402630863872, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'conspiratorial', 'score_1': 0.6230767247438818, 'score_2': -2.901556568255976, 'score_3': -1.7233488031688415, 'score4': 0.4141316981173892},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'conspiratorial', 'score_1': 0.5422717948190618, 'score_2': -2.6824805710639805, 'score_3': -1.8438333095102444, 'score4': 1.069268985483234},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'conspiratorial', 'score_1': -0.11834856355440686, 'score_2': -2.0923119773823093, 'score_3': -2.50062267511351, 'score4': -0.350292001144928},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'conspiratorial', 'score_1': 0.4199517970379373, 'score_2': -1.651038973191462, 'score_3': -1.5294489176432593, 'score4': 0.4036153625479281},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'conspiratorial', 'score_1': 1.492761147643538, 'score_2': -1.5121322447698295, 'score_3': -0.6249482337788942, 'score4': 1.1697522119955668},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'religious', 'score_1': 0.5600850935866192, 'score_2': -0.40343499951634487, 'score_3': 0.3105193944696587, 'score4': 0.6225164998419712},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'religious', 'score_1': 1.9239493593443395, 'score_2': -0.2346955905744602, 'score_3': 0.7391465145199775, 'score4': 1.0067377883300832},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'religious', 'score_1': 2.9049956518754514, 'score_2': -0.44754761968131884, 'score_3': 2.053337381081336, 'score4': 2.0763213081172727},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'religious', 'score_1': -1.7194092716022353, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'religious', 'score_1': 1.1330742287383677, 'score_2': -2.762339225284954, 'score_3': -1.108400219060862, 'score4': 1.1591206404604417},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'religious', 'score_1': 0.5910095298042546, 'score_2': -1.3525596981178438, 'score_3': -1.5160375069907694, 'score4': 0.04860668223953327},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'religious', 'score_1': 0.8960678767291325, 'score_2': -3.3131494266795913, 'score_3': -1.588617227292133, 'score4': 1.425208571144558},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'religious', 'score_1': 0.7762813901412428, 'score_2': -2.124523176572092, 'score_3': -1.2723002933256289, 'score4': 1.0665947666488813},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'religious', 'score_1': 1.232476136276779, 'score_2': -1.2062685445787034, 'score_3': -0.24352318929080902, 'score4': 1.0399876333446891},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'racist', 'score_1': 0.5202890196057048, 'score_2': -0.5879370287916934, 'score_3': 0.5773471182618114, 'score4': 0.9377080943319853},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'racist', 'score_1': 1.9570528310018884, 'score_2': 0.4717302217892633, 'score_3': -0.0030193639626645897, 'score4': -0.44694534798933944},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'racist', 'score_1': 2.438709994543979, 'score_2': 0.10976684150585707, 'score_3': 0.7957729031192907, 'score4': 0.5014649920173814},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'racist', 'score_1': 1.135536169157908, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'racist', 'score_1': 0.3767538928885483, 'score_2': -2.664976543012052, 'score_3': -1.5716661933542182, 'score4': 0.577262328554038},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'racist', 'score_1': -0.1004974240098965, 'score_2': -2.640223181365992, 'score_3': -2.9135935999758256, 'score4': -0.4035225522733695},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'racist', 'score_1': 1.2937117533938827, 'score_2': -2.5944388152347018, 'score_3': -1.5467581812937106, 'score4': 0.7837856557141005},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'racist', 'score_1': 1.6230308710814365, 'score_2': -1.5411236701188427, 'score_3': -0.519053297335181, 'score4': 1.2473464172895266},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'racist', 'score_1': 1.9311961596623788, 'score_2': -1.1768183758777553, 'score_3': -0.4875393919020686, 'score4': 0.9410673686017741},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'ethic', 'score_1': -0.39947358956528545, 'score_2': -0.5270253324323813, 'score_3': -0.32505115528963535, 'score4': 0.01878044211621178},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'ethic', 'score_1': 1.6088798603352006, 'score_2': 0.35903963867135374, 'score_3': 0.2223680311538613, 'score4': -0.06218801267498672},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'ethic', 'score_1': 2.4354615840316263, 'score_2': -0.1057358829808476, 'score_3': 0.9610940439985542, 'score4': 0.8901727903010912},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'ethic', 'score_1': -1.5915251383133922, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'ethic', 'score_1': 0.5963494988229359, 'score_2': -2.283684740422881, 'score_3': -1.758792945614139, 'score4': 0.014149686767845795},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'ethic', 'score_1': 1.062149218502879, 'score_2': -1.7366217431474615, 'score_3': -1.337473540213309, 'score4': 0.5434804260221586},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'ethic', 'score_1': 0.4707221058658645, 'score_2': -3.047295544522799, 'score_3': -2.5325874920981613, 'score4': 0.1847843060470109},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'ethic', 'score_1': 0.8126265426531175, 'score_2': -1.047589814667108, 'score_3': -0.8830592213983445, 'score4': 0.44912693117001734},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'ethic', 'score_1': 1.3252548383674532, 'score_2': -0.9916203057665253, 'score_3': -0.7393694281693199, 'score4': 0.4265848456067582},


]

anticommunism_scores_2 = [

{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'sentiment', 'score_1': 1.1612850452796626},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'sentiment', 'score_1': -0.6680285938489869},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'sentiment', 'score_1': -0.7822826242953418},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'sentiment', 'score_1': -0.44497206512240894},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'sentiment', 'score_1': -0.5842566637081387},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'sentiment', 'score_1': -1.9639605530109336},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'sentiment', 'score_1': -1.111533161275397},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'sentiment', 'score_1': -0.05076842027944556},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'sentiment', 'score_1': -0.024731269258014856},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'political', 'score_1': 0.325298939681413},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'political', 'score_1': -0.05910341493423487},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'political', 'score_1': -0.8180209907852568},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'political', 'score_1': -0.510742010177012},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'political', 'score_1': 0.6625626336011858},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'political', 'score_1': 0.16707851364245033},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'political', 'score_1': -0.3522767704744922},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'political', 'score_1': 0.346606237267954},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'political', 'score_1': -0.08255322305025824},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'propaganda', 'score_1': 0.2831066879139745},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'propaganda', 'score_1': 1.0897791393134286},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'propaganda', 'score_1': -0.28972805648108607},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'propaganda', 'score_1': 0.41308676802418176},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'propaganda', 'score_1': -0.18968294051690437},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'propaganda', 'score_1': 0.5926158549794259},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'propaganda', 'score_1': -1.3007753521273986},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'propaganda', 'score_1': 1.2429396377642759},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'propaganda', 'score_1': -0.6479950189087105},
           
]

anticommunism_scores_5 = [

{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'sentiment', 'score_1': 0.9674224702105676},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'sentiment', 'score_1': -0.2961199761011436},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'sentiment', 'score_1': -0.1931130643743601},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'sentiment', 'score_1': 0.9609902993856384},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'sentiment', 'score_1': -1.4026000760215598},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'sentiment', 'score_1': -1.9928540331014402},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'sentiment', 'score_1': -0.29032543888448575},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'sentiment', 'score_1': -0.66584850762854},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'sentiment', 'score_1': 0.2103485642389707},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'political', 'score_1': 0.3253055877172303},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'political', 'score_1': -0.2484057442045563},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'political', 'score_1': -0.4834666567131182},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'political', 'score_1': 0.7240281979224236},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'political', 'score_1': 0.492767344187777},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'political', 'score_1': 0.16725621292627568},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'political', 'score_1': 0.9056106752483203},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'political', 'score_1': -0.44778508566856684},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'political', 'score_1': 0.6229447617235171},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'propaganda', 'score_1': 0.29006546945524314},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'propaganda', 'score_1': 2.274442023330604},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'propaganda', 'score_1': 0.11791125401467746},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'propaganda', 'score_1': 0.6344561156705424},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'propaganda', 'score_1': -0.5338934515276944},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'propaganda', 'score_1': 0.58834120312497},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'propaganda', 'score_1': -0.6043116751010731},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'propaganda', 'score_1': -0.2854128759501817},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'propaganda', 'score_1': -0.7458401059325573},
            
]

anticommunism_scores_10 = [


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'sentiment', 'score_1': 0.9198868764450792},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'sentiment', 'score_1': -0.1555445613034906},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'sentiment', 'score_1': 0.0984376408836441},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'sentiment', 'score_1': -0.4607921881913523},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'sentiment', 'score_1': -1.7013471006580398},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'sentiment', 'score_1': -2.053148089457431},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'sentiment', 'score_1': -0.0172129023447298},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'sentiment', 'score_1': -1.4833284320428357},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'sentiment', 'score_1': -0.2244872772957883},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'political', 'score_1': -0.17070927751757936},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'political', 'score_1': -0.333308409881082},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'political', 'score_1': -0.2501289370604743},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'political', 'score_1': -0.0765679644355955},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'political', 'score_1': 0.49205750181793606},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'political', 'score_1': -0.018061846400961132},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'political', 'score_1': 1.536717585335587},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'political', 'score_1': -0.921899427686335},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'political', 'score_1': 0.08698674455609369},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'propaganda', 'score_1': 0.26022453731367307},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'propaganda', 'score_1': 2.2412648264481976},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'propaganda', 'score_1': 0.08096855131469673},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'propaganda', 'score_1': -0.6380255568973178},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'propaganda', 'score_1': -0.4404566394053806},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'propaganda', 'score_1': -0.09646720416142794},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'propaganda', 'score_1': -0.18453035482145735},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'propaganda', 'score_1': -0.4219859002386768},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'propaganda', 'score_1': -0.9948204932509385},

]

antisemitism_scores_2 = [
                         
                         
]

antisemitism_scores_5 = [


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'sentiment', 'score_1': 0.42748264764620514, 'score_2': -0.20940041521001415, 'score_3': 0.14282334640793473, 'score4': 0.2617240386790354},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'sentiment', 'score_1': 2.1220533470717386, 'score_2': 0.14711130214654314, 'score_3': 0.4120577291966645, 'score4': 0.340717138261302},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'sentiment', 'score_1': 1.803197719632043, 'score_2': -1.232116243949735, 'score_3': -0.33871210510402566, 'score4': 1.068198076916197},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'sentiment', 'score_1': 1.1258893417832474, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'sentiment', 'score_1': 2.8089425009096254, 'score_2': -2.0919100701302487, 'score_3': 0.3461033035006078, 'score4': 1.9752393035399107},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'sentiment', 'score_1': 1.9746303312594338, 'score_2': -3.914439473359278, 'score_3': 0.7845225314113896, 'score4': 4.348709482529624},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'sentiment', 'score_1': 2.2576237077848123, 'score_2': -0.5264034326341002, 'score_3': -0.011924145823576818, 'score4': 0.45303231161029556},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'sentiment', 'score_1': 2.581906106291863, 'score_2': -1.3051343432433389, 'score_3': 1.0982400338150478, 'score4': 2.8520370999455533},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'sentiment', 'score_1': 0.9661952978221905, 'score_2': -1.4210079399832067, 'score_3': -0.8934120277585428, 'score4': 0.884209332745646},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'patriotic', 'score_1': 0.6584845680199548, 'score_2': -0.7668900960628149, 'score_3': 0.26476255054660447, 'score4': 0.7635713964147434},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'patriotic', 'score_1': 0.4494945570933738, 'score_2': -0.1282701175743794, 'score_3': -1.4967594516499376, 'score4': -1.5851320312435293},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'patriotic', 'score_1': 2.3250933374125, 'score_2': -1.026831923226574, 'score_3': -0.34745035813534764, 'score4': 0.8759276948141717},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'patriotic', 'score_1': -0.7891172825313508, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'patriotic', 'score_1': 2.3839929229261885, 'score_2': -2.7318489549212894, 'score_3': -0.12190137118186448, 'score4': 1.8975573303655544},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'patriotic', 'score_1': 1.025323105549742, 'score_2': -2.497928107851204, 'score_3': -0.5847140022133734, 'score4': 1.6333695241796486},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'patriotic', 'score_1': 0.8663724067612527, 'score_2': -1.0354391348280005, 'score_3': -1.9092631222867922, 'score4': -0.31304429028875735},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'patriotic', 'score_1': 0.15423620585804693, 'score_2': -1.6005635694197708, 'score_3': -1.7014105226861753, 'score4': -0.19876852653003727},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'patriotic', 'score_1': 0.5622453400088412, 'score_2': -0.9701738854341616, 'score_3': -1.646504143128953, 'score4': -0.7026836088992376},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'economic', 'score_1': 0.43316047635119115, 'score_2': -1.086076585023053, 'score_3': 0.24512160481005976, 'score4': 0.9369444848192899},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'economic', 'score_1': 2.415322382196986, 'score_2': 0.2156921023843054, 'score_3': 0.7560481957646813, 'score4': 0.6767394639864512},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'economic', 'score_1': 2.3622864533219676, 'score_2': -0.7344195654319013, 'score_3': 0.3986707955193434, 'score4': 1.2434942813022634},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'economic', 'score_1': -0.4711258676571052, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'economic', 'score_1': 1.6330209317284456, 'score_2': -2.5172365449543928, 'score_3': -0.6654597567832269, 'score4': 1.1672244049632252},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'economic', 'score_1': 0.7715922989326971, 'score_2': -2.6149290952354747, 'score_3': -1.4954432054583349, 'score4': 1.1603749031052548},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'economic', 'score_1': 1.0127115122033241, 'score_2': -0.9280904037676242, 'score_3': -1.5441393278617714, 'score4': -0.21750590298431544},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'economic', 'score_1': 1.2524546221517545, 'score_2': -1.7153800200461715, 'score_3': -0.8400838193461576, 'score4': 1.0967731626937172},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'economic', 'score_1': 1.0128983284562634, 'score_2': -0.4698683334898596, 'score_3': -1.3083399617730331, 'score4': -0.7177695349530697},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'conspiratorial', 'score_1': 0.1672950109283283, 'score_2': -0.46066240492022453, 'score_3': 0.3013063518633753, 'score4': 0.5803474496610228},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'conspiratorial', 'score_1': 0.35505614428897847, 'score_2': 0.2129578034748594, 'score_3': -1.209817697595474, 'score4': -1.5809354807130347},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'conspiratorial', 'score_1': 2.5887059938225425, 'score_2': -1.0865045999010838, 'score_3': 0.3557306814032353, 'score4': 1.666763402028345},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'conspiratorial', 'score_1': -1.807739233174468, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'conspiratorial', 'score_1': 1.2590861537073748, 'score_2': -2.87452914462038, 'score_3': -0.9783258983126475, 'score4': 0.9720955926353625},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'conspiratorial', 'score_1': 0.6382164504211953, 'score_2': -3.872391476219626, 'score_3': -1.4183116167042165, 'score4': 2.050317593117371},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'conspiratorial', 'score_1': 0.017699489232590047, 'score_2': -0.7793874192564155, 'score_3': -2.4613715657914064, 'score4': -1.0717337695192433},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'conspiratorial', 'score_1': 0.854156301385352, 'score_2': -1.4833337464960505, 'score_3': -1.3978058260313941, 'score4': 0.3250525331560286},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'conspiratorial', 'score_1': 1.1258792798035062, 'score_2': -1.2298234086478246, 'score_3': -1.066312582073101, 'score4': 0.4141216242183664},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'religious', 'score_1': 0.5748164708435894, 'score_2': -0.6035641937775266, 'score_3': 0.5034451982484456, 'score4': 0.9164918660461383},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'religious', 'score_1': 1.923651089247659, 'score_2': -0.23522798342831217, 'score_3': 0.739188005177968, 'score4': 1.007221013204464},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'religious', 'score_1': 2.840908242995226, 'score_2': -0.6565852726288981, 'score_3': 0.9495073845842107, 'score4': 1.6748094327255827},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'religious', 'score_1': -1.2056943149007295, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'religious', 'score_1': 1.4655481263117007, 'score_2': -3.0167564170319405, 'score_3': -0.536875763335413, 'score4': 1.6744181816696213},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'religious', 'score_1': 0.5169007438225379, 'score_2': -2.1210234578572296, 'score_3': -1.581091845770689, 'score4': 0.4445416909245942},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'religious', 'score_1': 0.9222139629392222, 'score_2': -1.1831225915119865, 'score_3': -1.666857301817149, 'score4': -0.04728052164630974},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'religious', 'score_1': 0.8034516451585614, 'score_2': -2.0967998842648874, 'score_3': -1.065313791222169, 'score4': 1.2458689906767946},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'religious', 'score_1': 0.6582467890635665, 'score_2': -1.178311376028708, 'score_3': -1.2603766923326198, 'score4': 0.12861206524594232},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'racist', 'score_1': 0.33582850751792087, 'score_2': -0.871739146328085, 'score_3': 0.452351012326332, 'score4': 0.9282103551314148},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'racist', 'score_1': 1.9458559938104567, 'score_2': 0.46546080127559336, 'score_3': -0.007201226959702842, 'score4': -0.44572888608908234},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'racist', 'score_1': 2.5814663672972307, 'score_2': -0.4096845629760624, 'score_3': 0.12171066486759104, 'score4': 0.5673469024536849},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'racist', 'score_1': 1.1941854986261886, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'racist', 'score_1': 1.1214189423924217, 'score_2': -2.7249620474726437, 'score_3': -0.8252509593171594, 'score4': 1.131617557502056},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'racist', 'score_1': 0.048477942554165106, 'score_2': -3.745247333269539, 'score_3': -2.699031750801977, 'score4': 0.3981805058644363},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'racist', 'score_1': 1.365171487180761, 'score_2': -0.7030634729379694, 'score_3': -1.553552061616902, 'score4': -0.4219265443656566},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'racist', 'score_1': 1.869674703899408, 'score_2': -1.4011129825107504, 'score_3': -0.4183085350016429, 'score4': 1.184191404281444},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'racist', 'score_1': 1.2683525803997944, 'score_2': -1.0935637597497831, 'score_3': -1.125660828351404, 'score4': 0.22407718277671523},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'ethic', 'score_1': -0.2369864014061536, 'score_2': -0.7008611995658951, 'score_3': -0.05380900202160472, 'score4': 0.3702778464912789},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'ethic', 'score_1': 1.608550045407153, 'score_2': 0.358514445076785, 'score_3': 0.22224810314374974, 'score4': -0.061888817388381756},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'ethic', 'score_1': 2.588136149448095, 'score_2': -0.6291525155863236, 'score_3': 0.26351510896003544, 'score4': 0.9856911499240489},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'ethic', 'score_1': -0.8661810341119073, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'ethic', 'score_1': 1.3865998534209152, 'score_2': -2.3439111384850935, 'score_3': -0.9518724927715616, 'score4': 0.7026875951210967},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'ethic', 'score_1': 1.0605587525338969, 'score_2': -2.78903233153792, 'score_3': -1.1468202704138273, 'score4': 1.4720669672947948},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'ethic', 'score_1': 0.5587629190406009, 'score_2': -1.0157883039636522, 'score_3': -2.531967780406663, 'score4': -0.8867971409704225},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'ethic', 'score_1': 1.16752704238256, 'score_2': -0.9725263229385942, 'score_3': -0.6831118144554965, 'score4': 0.49026064904351496},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'ethic', 'score_1': 0.8418994933887117, 'score_2': -0.9691916210477455, 'score_3': -1.2857173736383811, 'score4': -0.10956707540931339},
          
]

antisemitism_scores_10 = [


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'sentiment', 'score_1': 0.37670222200402464, 'score_2': -0.005299272610730026, 'score_3': -0.1005426408747933, 'score4': -0.09656219631595123},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'sentiment', 'score_1': 2.119377859966723, 'score_2': 0.1430430297007514, 'score_3': 0.4086986026541192, 'score4': 0.34027764551077605},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'sentiment', 'score_1': 1.5636696729757658, 'score_2': -0.8413002471351207, 'score_3': 0.19445380632826673, 'score4': 0.9159093861067269},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'sentiment', 'score_1': 0.9573937381168157, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'sentiment', 'score_1': 2.086692426010238, 'score_2': -1.9864471852427699, 'score_3': -0.6126513787372713, 'score4': 1.1433849792296389},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'sentiment', 'score_1': 2.3385925723215295, 'score_2': -2.8658585205066323, 'score_3': 0.5659282063325999, 'score4': 3.4722871826079995},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'sentiment', 'score_1': 2.236918679757371, 'score_2': -2.670563518100511, 'score_3': 0.05180901755172614, 'score4': 2.2984952329388797},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'sentiment', 'score_1': 2.574988097947276, 'score_2': -1.3147674196303807, 'score_3': 1.1083220722663298, 'score4': 3.07698986247166},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'sentiment', 'score_1': 1.5959697430745707, 'score_2': -1.6189875255172632, 'score_3': 0.06037460221312991, 'score4': 2.1335998636097515},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'patriotic', 'score_1': 0.6264663422414063, 'score_2': -0.5503061558472059, 'score_3': 0.04975521922434832, 'score4': 0.45985352756975634},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'patriotic', 'score_1': 0.4497006269249871, 'score_2': -0.12789222918112547, 'score_3': -1.4964799987174373, 'score4': -1.5851977431894526},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'patriotic', 'score_1': 2.4354922664115697, 'score_2': -0.5588773459025083, 'score_3': 0.56450812682738, 'score4': 1.0104171532851058},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'patriotic', 'score_1': 0, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'patriotic', 'score_1': 1.753005027837147, 'score_2': -2.708172978162502, 'score_3': -0.7730086712669643, 'score4': 1.5412882069041958},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'patriotic', 'score_1': 1.3268614669166483, 'score_2': -1.4680344736325102, 'score_3': -0.44506543486795186, 'score4': 0.9290309570683057},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'patriotic', 'score_1': 0.7893871560056842, 'score_2': -2.9189534484681423, 'score_3': -1.9264151334344242, 'score4': 0.835193818333426},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'patriotic', 'score_1': -0.2952483992358144, 'score_2': -1.8632523419804898, 'score_3': -1.7657457790593678, 'score4': -0.1344136469554441},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'patriotic', 'score_1': 2.1691813528633865, 'score_2': -1.0358880307462626, 'score_3': -0.08109223331008768, 'score4': 1.1053033364089166},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'economic', 'score_1': 0.25808692851993387, 'score_2': -0.9969401079552502, 'score_3': -0.14102396142766274, 'score4': 0.5269990141142932},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'economic', 'score_1': 2.4045477806644846, 'score_2': 0.21703774279927615, 'score_3': 0.7541211087508518, 'score4': 0.6731483926035725},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'economic', 'score_1': 2.1871990417387956, 'score_2': -0.20903883025626185, 'score_3': 1.1342840005853423, 'score4': 1.124279714273823},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'economic', 'score_1': -0.46809572931896015, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'economic', 'score_1': 0.952699900071511, 'score_2': -2.5429698233556586, 'score_3': -1.4216260464370758, 'score4': 0.6351249453304479},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'economic', 'score_1': 0.6376729885777802, 'score_2': -1.6263416554655998, 'score_3': -1.7988125271078437, 'score4': 0.2610185871831942},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'economic', 'score_1': 0.9453730577679547, 'score_2': -2.7986907330200874, 'score_3': -1.5368854429673147, 'score4': 1.0594492795486818},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'economic', 'score_1': 0.9658203967373897, 'score_2': -1.8959831782543688, 'score_3': -0.9763044716408937, 'score4': 1.1790498251067023},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'economic', 'score_1': 1.3899392742952357, 'score_2': -0.2338856368493809, 'score_3': -0.9922476067712904, 'score4': -0.5293944899257207},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'conspiratorial', 'score_1': 0.25383880123793107, 'score_2': -0.3493278664899513, 'score_3': 0.0768535463192094, 'score4': 0.3031259270628789},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'conspiratorial', 'score_1': 0.3546223104304719, 'score_2': 0.2132336007549482, 'score_3': -1.2097626824637222, 'score4': -1.5810862970769777},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'conspiratorial', 'score_1': 2.3923101914527587, 'score_2': -0.633825209432788, 'score_3': 0.9771798867481873, 'score4': 1.4709552134881954},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'conspiratorial', 'score_1': -1.8344402630863872, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'conspiratorial', 'score_1': 0.6230767247438818, 'score_2': -2.901556568255976, 'score_3': -1.7233488031688415, 'score4': 0.4141316981173892},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'conspiratorial', 'score_1': 0.5422717948190618, 'score_2': -2.6824805710639805, 'score_3': -1.8438333095102444, 'score4': 1.069268985483234},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'conspiratorial', 'score_1': -0.11834856355440686, 'score_2': -2.0923119773823093, 'score_3': -2.50062267511351, 'score4': -0.350292001144928},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'conspiratorial', 'score_1': 0.4199517970379373, 'score_2': -1.651038973191462, 'score_3': -1.5294489176432593, 'score4': 0.4036153625479281},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'conspiratorial', 'score_1': 1.492761147643538, 'score_2': -1.5121322447698295, 'score_3': -0.6249482337788942, 'score4': 1.1697522119955668},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'religious', 'score_1': 0.5600850935866192, 'score_2': -0.40343499951634487, 'score_3': 0.3105193944696587, 'score4': 0.6225164998419712},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'religious', 'score_1': 1.9239493593443395, 'score_2': -0.2346955905744602, 'score_3': 0.7391465145199775, 'score4': 1.0067377883300832},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'religious', 'score_1': 2.9049956518754514, 'score_2': -0.44754761968131884, 'score_3': 2.053337381081336, 'score4': 2.0763213081172727},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'religious', 'score_1': -1.7194092716022353, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'religious', 'score_1': 1.1330742287383677, 'score_2': -2.762339225284954, 'score_3': -1.108400219060862, 'score4': 1.1591206404604417},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'religious', 'score_1': 0.5910095298042546, 'score_2': -1.3525596981178438, 'score_3': -1.5160375069907694, 'score4': 0.04860668223953327},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'religious', 'score_1': 0.8960678767291325, 'score_2': -3.3131494266795913, 'score_3': -1.588617227292133, 'score4': 1.425208571144558},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'religious', 'score_1': 0.7762813901412428, 'score_2': -2.124523176572092, 'score_3': -1.2723002933256289, 'score4': 1.0665947666488813},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'religious', 'score_1': 1.232476136276779, 'score_2': -1.2062685445787034, 'score_3': -0.24352318929080902, 'score4': 1.0399876333446891},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'racist', 'score_1': 0.5202890196057048, 'score_2': -0.5879370287916934, 'score_3': 0.5773471182618114, 'score4': 0.9377080943319853},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'racist', 'score_1': 1.9570528310018884, 'score_2': 0.4717302217892633, 'score_3': -0.0030193639626645897, 'score4': -0.44694534798933944},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'racist', 'score_1': 2.438709994543979, 'score_2': 0.10976684150585707, 'score_3': 0.7957729031192907, 'score4': 0.5014649920173814},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'racist', 'score_1': 1.135536169157908, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'racist', 'score_1': 0.3767538928885483, 'score_2': -2.664976543012052, 'score_3': -1.5716661933542182, 'score4': 0.577262328554038},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'racist', 'score_1': -0.1004974240098965, 'score_2': -2.640223181365992, 'score_3': -2.9135935999758256, 'score4': -0.4035225522733695},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'racist', 'score_1': 1.2937117533938827, 'score_2': -2.5944388152347018, 'score_3': -1.5467581812937106, 'score4': 0.7837856557141005},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'racist', 'score_1': 1.6230308710814365, 'score_2': -1.5411236701188427, 'score_3': -0.519053297335181, 'score4': 1.2473464172895266},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'racist', 'score_1': 1.9311961596623788, 'score_2': -1.1768183758777553, 'score_3': -0.4875393919020686, 'score4': 0.9410673686017741},


{'method': 'PPMI', 'slice': 'kaiserreich1', 'dimension': 'ethic', 'score_1': -0.39947358956528545, 'score_2': -0.5270253324323813, 'score_3': -0.32505115528963535, 'score4': 0.01878044211621178},
{'method': 'PPMI', 'slice': 'kaiserreich2', 'dimension': 'ethic', 'score_1': 1.6088798603352006, 'score_2': 0.35903963867135374, 'score_3': 0.2223680311538613, 'score4': -0.06218801267498672},
{'method': 'PPMI', 'slice': 'weimar', 'dimension': 'ethic', 'score_1': 2.4354615840316263, 'score_2': -0.1057358829808476, 'score_3': 0.9610940439985542, 'score4': 0.8901727903010912},
{'method': 'PPMI', 'slice': 'ns', 'dimension': 'ethic', 'score_1': -1.5915251383133922, 'score_2': 0, 'score_3': 0, 'score4': 0},
{'method': 'PPMI', 'slice': 'cdu1', 'dimension': 'ethic', 'score_1': 0.5963494988229359, 'score_2': -2.283684740422881, 'score_3': -1.758792945614139, 'score4': 0.014149686767845795},
{'method': 'PPMI', 'slice': 'spd1', 'dimension': 'ethic', 'score_1': 1.062149218502879, 'score_2': -1.7366217431474615, 'score_3': -1.337473540213309, 'score4': 0.5434804260221586},
{'method': 'PPMI', 'slice': 'cdu2', 'dimension': 'ethic', 'score_1': 0.4707221058658645, 'score_2': -3.047295544522799, 'score_3': -2.5325874920981613, 'score4': 0.1847843060470109},
{'method': 'PPMI', 'slice': 'spd2', 'dimension': 'ethic', 'score_1': 0.8126265426531175, 'score_2': -1.047589814667108, 'score_3': -0.8830592213983445, 'score4': 0.44912693117001734},
{'method': 'PPMI', 'slice': 'cdu3', 'dimension': 'ethic', 'score_1': 1.3252548383674532, 'score_2': -0.9916203057665253, 'score_3': -0.7393694281693199, 'score4': 0.4265848456067582},

                          
]

"""Plot Data to Chart"""

import seaborn as sns
from matplotlib import pyplot as plt
import pandas as pd
from google.colab import files
import numpy as np

def plot_all_lines(data, statistic, title):
  data_list = []
  for d in data:
    if d["method"] == statistic:
       d["view"] = d["dimension"]
       data_list.append(d)
  df = pd.DataFrame(data_list)
  sns.set_theme()

  g = sns.barplot(data=df,
      x="slice", 
      y="score_1", 
      hue="view", 
      alpha=.6, 
      palette="hls"
  )


  #g.despine(left=True)
  #g.set_axis_labels("", statistic)
  #g.legend.set_title("")

  plt.savefig(title + ".pdf")
  files.download(title + ".pdf")

plot_all_lines(anticommunism_scores_2, "PPMI", "anticommunism_scores_2")

plot_all_lines(anticommunism_scores_5, "PPMI", "anticommunism_scores_5")

plot_all_lines(anticommunism_scores_10, "PPMI", "anticommunism_scores_10")

plot_all_lines(antisemitism_scores_5, "PPMI", "antisemitism_scores_5")

plot_all_lines(antisemitism_scores_10, "PPMI", "antisemitism_scores_10")

plot_all_lines(antisemitism_test_original, "PPMI", "antisemitism_test_original")