# -*- coding: utf-8 -*-
"""Scores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/147Wz1hYoh4iGdRKDXcZMnpIO_QO_OCmz

# **Antisemitism - WEAT Data**
"""

antisemitism_original = [
          {"slice": "KR1", "specification": "antisemitism_sentiment", "measure": "WEAT", "score": 0.87, "significance": True},
          {"slice": "KR2", "specification": "antisemitism_sentiment", "measure": "WEAT", "score": 0.85, "significance": True},
          {"slice": "Weimar", "specification": "antisemitism_sentiment", "measure": "WEAT", "score": 0.82, "significance": True},
          {"slice": "CDU1", "specification": "antisemitism_sentiment", "measure": "WEAT", "score": 1.48, "significance": True},
          {"slice": "SPD1", "specification":"antisemitism_sentiment" , "measure": "WEAT", "score": 1.06, "significance": True},
          {"slice": "CDU2", "specification": "antisemitism_sentiment", "measure": "WEAT", "score": 1.35, "significance": True},
          {"slice": "SPD2", "specification": "antisemitism_sentiment" , "measure": "WEAT", "score": 0.95, "significance": True},
          {"slice": "CDU3", "specification": "antisemitism_sentiment", "measure": "WEAT", "score": 1.26, "significance": True},
          {"slice": "KR1", "specification": "antisemitism_sentiment", "measure": "ECT", "score": 0.648},
          {"slice": "KR2", "specification": "antisemitism_sentiment", "measure": "ECT", "score": 0.845},
          {"slice": "Weimar", "specification": "antisemitism_sentiment", "measure": "ECT", "score": 0.619},
          {"slice": "CDU1", "specification": "antisemitism_sentiment", "measure": "ECT", "score": 0.544},
          {"slice": "SPD1", "specification":"antisemitism_sentiment" , "measure": "ECT", "score": 0.71},
          {"slice": "CDU2", "specification": "antisemitism_sentiment", "measure": "ECT", "score": 0.809},
          {"slice": "SPD2", "specification": "antisemitism_sentiment" , "measure": "ECT", "score": 0.934},
          {"slice": "CDU3", "specification": "antisemitism_sentiment", "measure": "ECT", "score": 0.862},

          {"slice": "KR1", "specification": "antisemitism_patriotism", "measure": "WEAT", "score": 1.29, "significance": True},
          {"slice": "KR2", "specification": "antisemitism_patriotism", "measure": "WEAT", "score": 0.83, "significance": True},
          {"slice": "Weimar", "specification": "antisemitism_patriotism", "measure": "WEAT", "score": 1.39, "significance": True},
          {"slice": "CDU1", "specification": "antisemitism_patriotism", "measure": "WEAT", "score": 0.62, "significance": False},
          {"slice": "SPD1", "specification":"antisemitism_patriotism" , "measure": "WEAT", "score": 0.84, "significance": False},
          {"slice": "CDU2", "specification": "antisemitism_patriotism", "measure": "WEAT", "score": 0.60, "significance": False},
          {"slice": "SPD2", "specification": "antisemitism_patriotism" , "measure": "WEAT", "score": -0.34, "significance": True},
          {"slice": "CDU3", "specification": "antisemitism_patriotism", "measure": "WEAT", "score": -0.11, "significance": True},
          {"slice": "KR1", "specification": "antisemitism_patriotism", "measure": "ECT", "score": 0.463},
          {"slice": "KR2", "specification": "antisemitism_patriotism", "measure": "ECT", "score": 0.796},
          {"slice": "Weimar", "specification": "antisemitism_patriotism", "measure": "ECT", "score": 0.425},
          {"slice": "CDU1", "specification": "antisemitism_patriotism", "measure": "ECT", "score": 0.436},
          {"slice": "SPD1", "specification":"antisemitism_patriotism" , "measure": "ECT", "score": 0.569},
          {"slice": "CDU2", "specification": "antisemitism_patriotism", "measure": "ECT", "score": 0.418},
          {"slice": "SPD2", "specification": "antisemitism_patriotism" , "measure": "ECT", "score": 0.895},
          {"slice": "CDU3", "specification": "antisemitism_patriotism", "measure": "ECT", "score": 0.85},
          
          {"slice": "KR1", "specification": "antisemitism_economy", "measure": "WEAT", "score": -0.47, "significance": True},
          {"slice": "KR2", "specification": "antisemitism_economy", "measure": "WEAT", "score": 1.17, "significance": True},
          {"slice": "Weimar", "specification": "antisemitism_economy", "measure": "WEAT", "score": 0.82, "significance": True},
          {"slice": "CDU1", "specification": "antisemitism_economy", "measure": "WEAT", "score": 0.78, "significance": False},
          {"slice": "SPD1", "specification":"antisemitism_economy" , "measure": "WEAT", "score": 0.27, "significance": False},
          {"slice": "CDU2", "specification": "antisemitism_economy", "measure": "WEAT", "score": -0.14, "significance": True},
          {"slice": "SPD2", "specification": "antisemitism_economy" , "measure": "WEAT", "score": 0.42, "significance": True},
          {"slice": "CDU3", "specification": "antisemitism_economy", "measure": "WEAT", "score": 0.03, "significance": False},
          {"slice": "KR1", "specification": "antisemitism_economy", "measure": "ECT", "score": 0.789},
          {"slice": "KR2", "specification": "antisemitism_economy", "measure": "ECT", "score": 0.875},
          {"slice": "Weimar", "specification": "antisemitism_economy", "measure": "ECT", "score": 0.785},
          {"slice": "CDU1", "specification": "antisemitism_economy", "measure": "ECT", "score": 0.839},
          {"slice": "SPD1", "specification":"antisemitism_economy" , "measure": "ECT", "score": 0.916},
          {"slice": "CDU2", "specification": "antisemitism_economy", "measure": "ECT", "score": 0.856},
          {"slice": "SPD2", "specification": "antisemitism_economy" , "measure": "ECT", "score": 0.771},
          {"slice": "CDU3", "specification": "antisemitism_economy", "measure": "ECT", "score": 0.767},
          
          {"slice": "KR1", "specification": "antisemitism_conspiracy", "measure": "WEAT", "score": 0.88, "significance": True},
          {"slice": "KR2", "specification": "antisemitism_conspiracy", "measure": "WEAT", "score": 1.1, "significance": True},
          {"slice": "Weimar", "specification": "antisemitism_conspiracy", "measure": "WEAT", "score": 1.28, "significance": True},
          {"slice": "CDU1", "specification": "antisemitism_conspiracy", "measure": "WEAT", "score": 1.13, "significance": True},
          {"slice": "SPD1", "specification":"antisemitism_conspiracy" , "measure": "WEAT", "score": 0.22, "significance": False},
          {"slice": "CDU2", "specification": "antisemitism_conspiracy", "measure": "WEAT", "score": 0.27, "significance": False},
          {"slice": "SPD2", "specification": "antisemitism_conspiracy" , "measure": "WEAT", "score": 0.50, "significance": False},
          {"slice": "CDU3", "specification": "antisemitism_conspiracy", "measure": "WEAT", "score": 0.23, "significance": False},
          {"slice": "KR1", "specification": "antisemitism_conspiracy", "measure": "ECT", "score": 0.800},
          {"slice": "KR2", "specification": "antisemitism_conspiracy", "measure": "ECT", "score": 0.890},
          {"slice": "Weimar", "specification": "antisemitism_conspiracy", "measure": "ECT", "score": 0.752},
          {"slice": "CDU1", "specification": "antisemitism_conspiracy", "measure": "ECT", "score": 0.681},
          {"slice": "SPD1", "specification":"antisemitism_conspiracy" , "measure": "ECT", "score": 0.842},
          {"slice": "CDU2", "specification": "antisemitism_conspiracy", "measure": "ECT", "score": 0.847},
          {"slice": "SPD2", "specification": "antisemitism_conspiracy" , "measure": "ECT", "score": 0.957},
          {"slice": "CDU3", "specification": "antisemitism_conspiracy", "measure": "ECT", "score": 0.936},
          
          {"slice": "KR1", "specification": "antisemitism_religion", "measure": "WEAT", "score": 0.70, "significance": False},
          {"slice": "KR2", "specification": "antisemitism_religion", "measure": "WEAT", "score": 0.61, "significance": False},
          {"slice": "Weimar", "specification": "antisemitism_religion", "measure": "WEAT", "score": 1.32, "significance": True},
          {"slice": "CDU1", "specification": "antisemitism_religion", "measure": "WEAT", "score": 1.1, "significance": True},
          {"slice": "SPD1", "specification":"antisemitism_religion" , "measure": "WEAT", "score": 0.79, "significance": False},
          {"slice": "CDU2", "specification": "antisemitism_religion", "measure": "WEAT", "score": 0.66, "significance": False},
          {"slice": "SPD2", "specification": "antisemitism_religion" , "measure": "WEAT", "score": -0.57, "significance": True},
          {"slice": "CDU3", "specification": "antisemitism_religion", "measure": "WEAT", "score": -0.57, "significance": False},
          {"slice": "KR1", "specification": "antisemitism_religion", "measure": "ECT", "score": 0.546},
          {"slice": "KR2", "specification": "antisemitism_religion", "measure": "ECT", "score": 0.641},
          {"slice": "Weimar", "specification": "antisemitism_religion", "measure": "ECT", "score": 0.251},
          {"slice": "CDU1", "specification": "antisemitism_religion", "measure": "ECT", "score": 0.851},
          {"slice": "SPD1", "specification":"antisemitism_religion" , "measure": "ECT", "score": 0.797},
          {"slice": "CDU2", "specification": "antisemitism_religion", "measure": "ECT", "score": 0.811},
          {"slice": "SPD2", "specification": "antisemitism_religion" , "measure": "ECT", "score": 0.894},
          {"slice": "CDU3", "specification": "antisemitism_religion", "measure": "ECT", "score": 0.955},
          
          {"slice": "KR1", "specification": "antisemitism_racism", "measure": "WEAT", "score": 1.22, "significance": True},
          {"slice": "KR2", "specification": "antisemitism_racism", "measure": "WEAT", "score": 1.18, "significance": True},
          {"slice": "Weimar", "specification": "antisemitism_racism", "measure": "WEAT", "score": 1.36, "significance": True},
          {"slice": "CDU1", "specification": "antisemitism_racism", "measure": "WEAT", "score": 1.39, "significance": True},
          {"slice": "SPD1", "specification":"antisemitism_racism" , "measure": "WEAT", "score": 0.52, "significance": False},
          {"slice": "CDU2", "specification": "antisemitism_racism", "measure": "WEAT", "score": 1.55, "significance": True},
          {"slice": "SPD2", "specification": "antisemitism_racism" , "measure": "WEAT", "score": 0.70, "significance": False},
          {"slice": "CDU3", "specification": "antisemitism_racism", "measure": "WEAT", "score": 0.72, "significance": False},
          {"slice": "KR1", "specification": "antisemitism_racism", "measure": "ECT", "score": 0.782},
          {"slice": "KR2", "specification": "antisemitism_racism", "measure": "ECT", "score": 0.900},
          {"slice": "Weimar", "specification": "antisemitism_racism", "measure": "ECT", "score": 0.846},
          {"slice": "CDU1", "specification": "antisemitism_racism", "measure": "ECT", "score": 0.661},
          {"slice": "SPD1", "specification":"antisemitism_racism" , "measure": "ECT", "score": 0.692},
          {"slice": "CDU2", "specification": "antisemitism_racism", "measure": "ECT", "score": 0.623},
          {"slice": "SPD2", "specification": "antisemitism_racism" , "measure": "ECT", "score": 0.871},
          {"slice": "CDU3", "specification": "antisemitism_racism", "measure": "ECT", "score": 0.817},
          
          {"slice": "KR1", "specification": "antisemitism_ethics", "measure": "WEAT", "score": 1.02, "significance": True},
          {"slice": "KR2", "specification": "antisemitism_ethics", "measure": "WEAT", "score": 1.15, "significance": True},
          {"slice": "Weimar", "specification": "antisemitism_ethics", "measure": "WEAT", "score": 1.11, "significance": True},
          {"slice": "CDU1", "specification": "antisemitism_ethics", "measure": "WEAT", "score": 1.22, "significance": True},
          {"slice": "SPD1", "specification":"antisemitism_ethics" , "measure": "WEAT", "score": 0.14, "significance": False},
          {"slice": "CDU2", "specification": "antisemitism_ethics", "measure": "WEAT", "score": 0.14, "significance": False},
          {"slice": "SPD2", "specification": "antisemitism_ethics" , "measure": "WEAT", "score": 0.17, "significance": False},
          {"slice": "CDU3", "specification": "antisemitism_ethics", "measure": "WEAT", "score": 0.07, "significance": False},
          {"slice": "KR1", "specification": "antisemitism_ethics", "measure": "ECT", "score": 0.327},
          {"slice": "KR2", "specification": "antisemitism_ethics", "measure": "ECT", "score": 0.577},
          {"slice": "Weimar", "specification": "antisemitism_ethics", "measure": "ECT", "score": 0.418},
          {"slice": "CDU1", "specification": "antisemitism_ethics", "measure": "ECT", "score": 0.421},
          {"slice": "SPD1", "specification":"antisemitism_ethics" , "measure": "ECT", "score": 0.884},
          {"slice": "CDU2", "specification": "antisemitism_ethics", "measure": "ECT", "score": 0.922},
          {"slice": "SPD2", "specification": "antisemitism_ethics" , "measure": "ECT", "score": 0.951},
          {"slice": "CDU3", "specification": "antisemitism_ethics", "measure": "ECT", "score": 0.937},
          
          
          {"slice": "KR1", "specification": "antisemitism", "measure": "KM", "score": 0.634},
          {"slice": "KR2", "specification": "antisemitism", "measure": "KM", "score": 0.662},
          {"slice": "Weimar", "specification": "antisemitism", "measure": "KM", "score": 0.643},
          {"slice": "CDU1", "specification": "antisemitism", "measure": "KM", "score": 0.636},
          {"slice": "SPD1", "specification":"antisemitism" , "measure": "KM", "score": 0.588},
          {"slice": "CDU2", "specification": "antisemitism", "measure": "KM", "score": 0.627},
          {"slice": "SPD2", "specification": "antisemitism" , "measure": "KM", "score": 0.580},
          {"slice": "CDU3", "specification": "antisemitism", "measure": "KM", "score": 0.54}]

antisemitism_recomputed = [
    {'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.872007, 'significance': False}, 
    {'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.84779686, 'significance': False}, 
    {'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.8168018, 'significance': False},
    {'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.4783529, 'significance': False},
    {'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.0569332, 'significance': False},  
    {'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.346908, 'significance': False},
    {'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.9541263, 'significance': False},  
    {'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.2641466, 'significance': False},

    {'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.2909055, 'significance': False}, 
    {'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.8280807, 'significance': False},
    {'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.3853147, 'significance': False},  
    {'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.62463105, 'significance': False},
    {'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.83941495, 'significance': False}, 
    {'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.59819996, 'significance': False},
    {'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': -0.33883572, 'significance': False}, 
    {'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': -0.11337078, 'significance': False},

    {'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.47426552, 'significance': False}, 
    {'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 1.1711416, 'significance': False}, 
    {'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.8233372, 'significance': False}, 
    {'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.78306973, 'significance': False},
    {'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.26511797, 'significance': False},  
    {'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.13619849, 'significance': False}, 
    {'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.4246332, 'significance': False}, 
    {'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.026193393, 'significance': False},  

    {'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.87771034, 'significance': False},
    {'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.1017394, 'significance': False},
    {'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.2783868, 'significance': False},
    {'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.1267052, 'significance': False}, 
    {'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.21989726, 'significance': False},
    {'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.2655984, 'significance': False},
    {'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.49977076, 'significance': False},
    {'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.2325401, 'significance': False},
    
    {'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.6992524, 'significance': False}, 
    {'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.6082763, 'significance': False}, 
    {'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.3218192, 'significance': False}, 
    {'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.1015065, 'significance': False},
    {'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.7886754, 'significance': False}, 
    {'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.6555432, 'significance': False}, 
    {'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.5704105, 'significance': False}, 
    {'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.5677645, 'significance': False}, 
    
    {'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.2176365, 'significance': False}, 
    {'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.1797507, 'significance': False}, 
    {'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.3589967, 'significance': False}, 
    {'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.3863708, 'significance': False},
    {'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.5167582, 'significance': False},  
    {'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.5539856, 'significance': False},
    {'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.69521964, 'significance': False}, 
    {'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.7221575, 'significance': False}, 
          
    {'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.0241079, 'significance': False},
    {'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.1529142, 'significance': False},
    {'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.113936, 'significance': False}, 
    {'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.2210681, 'significance': False}, 
    {'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.13973571, 'significance': False}, 
    {'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.135514, 'significance': False},
    {'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.16628915, 'significance': False}, 
    {'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.06643388, 'significance': False},    

    {'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6482176360225141},
{'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8447116867098365},
{'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6194503171247356},
{'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.5437632135306553},
{'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.7102083962549078},
{'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.808695652173913},
{'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.9343199436222691},
{'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8528522972556275},


{'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.46336996336996333},
{'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.7963875205254516},
{'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.42490842490842484},
{'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.4360902255639097},
{'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.5686274509803922},
{'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.4179566563467492},
{'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.8951048951048951},
{'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.8642857142857141},


{'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7894736842105263},
{'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8754940711462451},
{'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7845849802371542},
{'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.83859649122807},
{'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.9157894736842105},
{'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8556390977443609},
{'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7714285714285712},
{'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.801503759398496},


{'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7995967741935484},
{'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8899193548387098},
{'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7516129032258065},
{'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.6809788654060066},
{'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8423387096774193},
{'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8469410456062292},
{'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9566502463054185},
{'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9133064516129032},


{'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.5464426877470356},
{'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.641304347826087},
{'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.2506493506493506},
{'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.8511278195488721},
{'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.7965686274509804},
{'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.8105263157894737},
{'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.8941176470588235},
{'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.9587203302373581},


{'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.7817733990147782},
{'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8998887652947719},
{'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8460511679644049},
{'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.6605116796440489},
{'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.6918445539135194},
{'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.6226600985221674},
{'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8711843711843712},
{'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.810071154898741},


{'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.32695652173913037},
{'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.5765217391304347},
{'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.41826086956521735},
{'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.42094861660079047},
{'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.8842105263157894},
{'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.922077922077922},
{'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9509803921568628},
{'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9609022556390976},

]

antisemitism_v1 = [
{'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.9799935, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.0547734, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.7563711, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.2946521, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.4192659, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.4705241, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.0431354, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.1473182, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.3300031, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.0499681, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.3349004, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.49525192, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.82823974, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.4891958, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': -0.22375998, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.35482135, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.13281496, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 1.2343506, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 1.0465018, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.4962204, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.28987542, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.13406035, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.6039487, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.18029155, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.88149613, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.1021922, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.0241759, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.33885676, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.4544817, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.26238126, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.28975233, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.2835011, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.5749949, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.540668, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.2096231, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.772126, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.1376003, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.16967681, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.38997003, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.4206945, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.2539551, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.4545534, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.2213316, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.2603128, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.77974844, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.4795742, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.41379845, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.49593407, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.90043265, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.4136785, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.1440417, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.1856248, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.43976122, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': -0.049767002, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.19525549, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.27660584, 'significance': False},

{'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6694183864915573},
{'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.7888374961455442},
{'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6387798248263364},
{'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.5909795630725863},
{'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.7005436424041075},
{'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8358310206598828},
{'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.9209302325581397},
{'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8728337958680235},


{'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.5189255189255189},
{'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.7093596059113301},
{'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.43223443223443225},
{'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.2541353383458646},
{'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.47368421052631576},
{'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.4674922600619195},
{'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.8251748251748254},
{'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.807142857142857},


{'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8345864661654135},
{'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8794466403162056},
{'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.6709486166007905},
{'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7754385964912281},
{'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8508771929824561},
{'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8676691729323308},
{'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7857142857142856},
{'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.6556390977443608},


{'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7955645161290323},
{'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8588709677419356},
{'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7588709677419356},
{'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.717908787541713},
{'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7995967741935484},
{'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.885650723025584},
{'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9650246305418716},
{'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9330645161290324},


{'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.6215415019762845},
{'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.6511857707509883},
{'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.24285714285714283},
{'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.7714285714285714},
{'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.7696078431372549},
{'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.7701754385964912},
{'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.9794117647058824},
{'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.9607843137254902},


{'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8354679802955662},
{'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8638487208008899},
{'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8242491657397107},
{'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.6658509454949945},
{'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.715927750410509},
{'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.5669950738916255},
{'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.9029304029304028},
{'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8204707170224411},


{'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.37217391304347824},
{'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.4982608695652173},
{'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.2817391304347826},
{'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.7470355731225298},
{'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.8706766917293233},
{'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.8831168831168831},
{'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9583333333333335},
{'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9458646616541352},

]

antisemitism_v2 = [

{'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.98017067, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.97214985, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.5125529, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.4506136, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.2142395, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.2577963, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.1596963, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.3164204, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.3623159, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.0825305, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.4459457, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.4977018, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.2587719, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.81125945, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.091599256, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': -0.11805838, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.28140327, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 1.1915253, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 1.0395664, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.15478551, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.4581802, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.15769123, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.6726135, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.38742277, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.8925906, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.1799222, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.99660856, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.6597944, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.48831362, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': -0.029829329, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.47104564, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.20723279, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.70488286, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.6998224, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.3363688, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.038315, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.80152696, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.3743943, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.9843436, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.5232345, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.3044516, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.2567528, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.2688833, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.307162, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.8855067, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.4416432, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.6219371, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.5082654, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.9129857, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.3080045, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.2030873, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.1603917, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.4094006, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.2019998, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.6334866, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.37539586, 'significance': False},

{'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6549718574108819},
{'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8274437249460376},
{'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6641498036846873},
{'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6940098661028893},
{'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.7281787979462399},
{'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8199198273203824},
{'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.9152924594785059},
{'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8397779833487512},


{'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.47496947496947495},
{'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.6573617952928298},
{'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.5244200244200244},
{'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.22857142857142856},
{'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.5294117647058824},
{'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.5294117647058824},
{'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.8181818181818183},
{'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.7678571428571428},


{'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8300751879699247},
{'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8725296442687748},
{'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7509881422924901},
{'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8543859649122807},
{'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8894736842105263},
{'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7774436090225564},
{'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8714285714285712},
{'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8150375939849623},


{'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7467741935483873},
{'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8560483870967743},
{'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7633064516129033},
{'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.6921023359288097},
{'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8116935483870968},
{'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8442714126807563},
{'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9157635467980293},
{'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9209677419354839},


{'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.6808300395256918},
{'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.7262845849802372},
{'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.07142857142857142},
{'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.825563909774436},
{'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.8700980392156864},
{'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.8578947368421052},
{'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.9676470588235294},
{'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.9463364293085655},


{'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8201970443349751},
{'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8438264738598443},
{'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8389321468298109},
{'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.6916573971078976},
{'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.7350848385331145},
{'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.6418719211822659},
{'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.927960927960928},
{'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8741105637657363},


{'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.36173913043478256},
{'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.5313043478260869},
{'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.3104347826086956},
{'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.45553359683794475},
{'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.8285714285714285},
{'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.916883116883117},
{'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9754901960784315},
{'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9157894736842105},

     
]

antisemitism_v3 = [
{'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.7728993, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.76501334, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.9445245, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.6247203, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.2176276, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.3846499, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 1.0036684, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'WEAT', 'score': 0.93648297, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.1786902, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.96665627, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.4565912, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.80115277, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 1.0466787, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.73942894, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': -0.08449287, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'WEAT', 'score': 0.0037274517, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.062043324, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 1.1071585, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 1.0659132, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.7187419, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.45062426, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': -0.11664757, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.73439896, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'WEAT', 'score': 0.2508234, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.6476372, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.9753447, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.1566538, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 1.1107394, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.3751211, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.2527926, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.16894495, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'WEAT', 'score': 0.31323656, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.6238901, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.45732537, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.3299925, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 1.0916337, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.96497786, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': 0.24918401, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.7229989, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'WEAT', 'score': -0.36849704, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.0992837, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.2789738, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.3061025, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.4551044, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.8455956, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 1.4220295, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.47816822, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'WEAT', 'score': 0.7589597, 'significance': False},


{'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.7230118, 'significance': False},
{'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.1958153, 'significance': False},
{'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.2563995, 'significance': False},
{'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 1.5116227, 'significance': False},
{'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.4601499, 'significance': False},
{'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.278804, 'significance': False},
{'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.43530244, 'significance': False},
{'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'WEAT', 'score': 0.2883272, 'significance': False},

{'slice': 'KR1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.5806754221388368},
{'slice': 'KR2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.7961147086031451},
{'slice': 'Weimar', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6165810933252794},
{'slice': 'CDU1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6473572938689217},
{'slice': 'SPD1', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.6837813349441257},
{'slice': 'CDU2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8419981498612396},
{'slice': 'SPD2', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.9454545454545454},
{'slice': 'CDU3', 'specification': 'antisemitism_sentiment', 'measure': 'ECT', 'score': 0.8329941412272587},


{'slice': 'KR1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.5488400488400489},
{'slice': 'KR2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.7246852764094143},
{'slice': 'Weimar', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.442002442002442},
{'slice': 'CDU1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.28421052631578947},
{'slice': 'SPD1', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.6181630546955624},
{'slice': 'CDU2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.5376676986584108},
{'slice': 'SPD2', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.9580419580419581},
{'slice': 'CDU3', 'specification': 'antisemitism_patriotism', 'measure': 'ECT', 'score': 0.7749999999999999},


{'slice': 'KR1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8661654135338346},
{'slice': 'KR2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8833992094861661},
{'slice': 'Weimar', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.66699604743083},
{'slice': 'CDU1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8087719298245614},
{'slice': 'SPD1', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8421052631578947},
{'slice': 'CDU2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8586466165413533},
{'slice': 'SPD2', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.7571428571428571},
{'slice': 'CDU3', 'specification': 'antisemitism_economic', 'measure': 'ECT', 'score': 0.8300751879699247},


{'slice': 'KR1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7903225806451613},
{'slice': 'KR2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8596774193548388},
{'slice': 'Weimar', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7520161290322581},
{'slice': 'CDU1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7583982202447163},
{'slice': 'SPD1', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.7766129032258066},
{'slice': 'CDU2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.8451612903225806},
{'slice': 'SPD2', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9536945812807879},
{'slice': 'CDU3', 'specification': 'antisemitism_conspiratorial', 'measure': 'ECT', 'score': 0.9016129032258066},


{'slice': 'KR1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.5316205533596838},
{'slice': 'KR2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.6699604743083005},
{'slice': 'Weimar', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.087012987012987},
{'slice': 'CDU1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.813533834586466},
{'slice': 'SPD1', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.8088235294117647},
{'slice': 'CDU2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.8491228070175438},
{'slice': 'SPD2', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.961764705882353},
{'slice': 'CDU3', 'specification': 'antisemitism_religious', 'measure': 'ECT', 'score': 0.9711042311661506},


{'slice': 'KR1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8507389162561575},
{'slice': 'KR2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8843159065628475},
{'slice': 'Weimar', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8660734149054505},
{'slice': 'CDU1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.7312569521690767},
{'slice': 'SPD1', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.783798576902025},
{'slice': 'CDU2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.5911330049261082},
{'slice': 'SPD2', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.9261294261294261},
{'slice': 'CDU3', 'specification': 'antisemitism_racist', 'measure': 'ECT', 'score': 0.8467432950191571},


{'slice': 'KR1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.3521739130434782},
{'slice': 'KR2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.6052173913043478},
{'slice': 'Weimar', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.3060869565217391},
{'slice': 'CDU1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.5286561264822135},
{'slice': 'SPD1', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.8180451127819548},
{'slice': 'CDU2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9246753246753248},
{'slice': 'SPD2', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9534313725490198},
{'slice': 'CDU3', 'specification': 'antisemitism_ethic', 'measure': 'ECT', 'score': 0.9413533834586465},

]

"""# Anticommunism - Data"""

anticommunism_original = [
          {"slice": "KR1", "specification": "conservatism_communism_sentiment", "measure": "WEAT", "score": 0.1234, "significance": False},
          {"slice": "KR2", "specification": "conservatism_communism_sentiment", "measure": "WEAT", "score": 0.5067, "significance": True},
          {"slice": "Weimar", "specification": "conservatism_communism_sentiment", "measure": "WEAT", "score": 1.0078, "significance": True},
          {"slice": "CDU1", "specification": "conservatism_communism_sentiment", "measure": "WEAT", "score": 1.0379, "significance": True},
          {"slice": "SPD1", "specification":"conservatism_communism_sentiment" , "measure": "WEAT", "score": 0.8728, "significance": True},
          {"slice": "CDU2", "specification": "conservatism_communism_sentiment", "measure": "WEAT", "score": 0.7898, "significance": True},
          {"slice": "SPD2", "specification": "conservatism_communism_sentiment" , "measure": "WEAT", "score": 0.6348, "significance": True},
          {"slice": "CDU3", "specification": "conservatism_communism_sentiment", "measure": "WEAT", "score": 0.5246, "significance": True},
          {"slice": "KR1", "specification": "conservatism_communism_sentiment", "measure": "ECT", "score": 0.8591},
          {"slice": "KR2", "specification": "conservatism_communism_sentiment", "measure": "ECT", "score": 0.9103},
          {"slice": "Weimar", "specification": "conservatism_communism_sentiment", "measure": "ECT", "score": 0.6347},
          {"slice": "CDU1", "specification": "conservatism_communism_sentiment", "measure": "ECT", "score": 0.5927},
          {"slice": "SPD1", "specification":"conservatism_communism_sentiment" , "measure": "ECT", "score": 0.6872},
          {"slice": "CDU2", "specification": "conservatism_communism_sentiment", "measure": "ECT", "score": 0.5925},
          {"slice": "SPD2", "specification": "conservatism_communism_sentiment" , "measure": "ECT", "score": 0.7025},
          {"slice": "CDU3", "specification": "conservatism_communism_sentiment", "measure": "ECT", "score": 0.3161},

          {"slice": "KR1", "specification": "conservatism_communism_political", "measure": "WEAT", "score": 0.1930, "significance": False},
          {"slice": "KR2", "specification": "conservatism_communism_political", "measure": "WEAT", "score": 0.2021, "significance": False},
          {"slice": "Weimar", "specification": "conservatism_communism_political", "measure": "WEAT", "score": 0.0078, "significance": False},
          {"slice": "CDU1", "specification": "conservatism_communism_political", "measure": "WEAT", "score": 1.3809, "significance": True},
          {"slice": "SPD1", "specification":"conservatism_communism_political" , "measure": "WEAT", "score": 1.2420, "significance": True},
          {"slice": "CDU2", "specification": "conservatism_communism_political", "measure": "WEAT", "score": 1.2166, "significance": True},
          {"slice": "SPD2", "specification": "conservatism_communism_political" , "measure": "WEAT", "score": 0.8206, "significance": True},
          {"slice": "CDU3", "specification": "conservatism_communism_political", "measure": "WEAT", "score": 1.1207, "significance": True},
          {"slice": "KR1", "specification": "conservatism_communism_political", "measure": "ECT", "score": 0.6666},
          {"slice": "KR2", "specification": "conservatism_communism_political", "measure": "ECT", "score": 0.6831},
          {"slice": "Weimar", "specification": "conservatism_communism_political", "measure": "ECT", "score": 0.5096},
          {"slice": "CDU1", "specification": "conservatism_communism_political", "measure": "ECT", "score": 0.3850},
          {"slice": "SPD1", "specification":"conservatism_communism_political" , "measure": "ECT", "score": 0.4670},
          {"slice": "CDU2", "specification": "conservatism_communism_political", "measure": "ECT", "score": 0.6636},
          {"slice": "SPD2", "specification": "conservatism_communism_political" , "measure": "ECT", "score": 0.6617},
          {"slice": "CDU3", "specification": "conservatism_communism_political", "measure": "ECT", "score": 0.3909},

          {"slice": "KR1", "specification": "conservatism_communism_propaganda", "measure": "WEAT", "score": 0.4253, "significance": True},
          {"slice": "KR2", "specification": "conservatism_communism_propaganda", "measure": "WEAT", "score": 0.4352, "significance": True},
          {"slice": "Weimar", "specification": "conservatism_communism_propaganda", "measure": "WEAT", "score": 0.7749, "significance": True},
          {"slice": "CDU1", "specification": "conservatism_communism_propaganda", "measure": "WEAT", "score": 1.0096, "significance": True},
          {"slice": "SPD1", "specification":"conservatism_communism_propaganda" , "measure": "WEAT", "score": 1.1920, "significance": True},
          {"slice": "CDU2", "specification": "conservatism_communism_propaganda", "measure": "WEAT", "score": 1.2009, "significance": True},
          {"slice": "SPD2", "specification": "conservatism_communism_propaganda" , "measure": "WEAT", "score": 0.9448, "significance": True},
          {"slice": "CDU3", "specification": "conservatism_communism_propaganda", "measure": "WEAT", "score": 1.1719, "significance": True},
          {"slice": "KR1", "specification": "conservatism_communism_propaganda", "measure": "ECT", "score": 0.7919},
          {"slice": "KR2", "specification": "conservatism_communism_propaganda", "measure": "ECT", "score": 0.8121},
          {"slice": "Weimar", "specification": "conservatism_communism_propaganda", "measure": "ECT", "score": 0.2939},
          {"slice": "CDU1", "specification": "conservatism_communism_propaganda", "measure": "ECT", "score": 0.6768},
          {"slice": "SPD1", "specification":"conservatism_communism_propaganda" , "measure": "ECT", "score": 0.6625},
          {"slice": "CDU2", "specification": "conservatism_communism_propaganda", "measure": "ECT", "score": 0.6097},
          {"slice": "SPD2", "specification": "conservatism_communism_propaganda" , "measure": "ECT", "score": 0.7177},
          {"slice": "CDU3", "specification": "conservatism_communism_propaganda", "measure": "ECT", "score": 0.2661}      
]

# Testwise ECT scores computed on Tobis data set
anticommunism_recomputed = [

{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.9006455848561111},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.8938689217758985},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.9249655619479783},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7157442670772223},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6337979094076656},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6587737843551796},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7586905437160685},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6556730091613813},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.73292589763178},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7312616259984681},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6152204836415363},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.632801161103048},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.5646717322632971},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6690856313497822},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6400228702115494},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.49304364398704015},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.8308300395256916},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.809559050262103},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6354070305272896},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6879032258064517},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6059491978609626},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7042016806722688},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6915106951871658},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7087853323147442},

{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.63575345, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.50501466, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.24251017, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.4450033, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.3533928, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.2066013, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.7419499, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.714616, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 0.28928876, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': -0.029419156, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': -0.2805338, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.4106069, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.4064311, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.4207296, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.1571951, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.2244179, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.6623363, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.46562737, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': -0.22406492, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.3073597, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.3969309, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.4163234, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.15579, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.3361892, 'significance': False},

]

anticommunism_v1 = [
                    
{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.6409056, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.4961122, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.3757349, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.5033693, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.3408239, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.0426596, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.55415237, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.858315, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 0.10329201, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 0.010917887, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 0.06237275, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.4752557, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.3447208, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.2565174, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.2172122, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.1516391, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.62872535, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.43247023, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.04674255, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.2322958, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.3956314, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.2757457, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.1791781, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.1624786, 'significance': False},

{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.9022769629689654},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.8892383595436323},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.9143610013175228},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7137022397891963},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6770965468639887},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6903820816864294},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7601127554615926},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6851063829787233},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7231474407944997},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7996247654784241},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6244665718349929},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.5805515239477503},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.5913941774097156},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7000483792936624},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6245473603964169},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.5165999618829806},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7592885375494071},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.8583369518019973},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6373469387755102},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7393695014662756},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.661096256684492},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6822001527883881},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6733384262796027},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7308123249299721},

]

anticommunism_v2 = [
{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.5671487, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.6884695, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.442009, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.599392, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.3049959, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.0188824, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.83329064, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.8568519, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 0.1356452, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': -0.008896602, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': -0.13353524, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.4913794, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.2998201, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.1711998, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.1930696, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.0976881, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.5983574, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.4997177, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': -0.09361731, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.2396802, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.3663015, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.2015448, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.0184937, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.2067037, 'significance': False},  

{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.8985495502795561},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.8891150169596053},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.9245059288537548},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6843214756258233},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7110641296687807},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.694729907773386},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7730796335447498},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7155720012334258},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7353705118411},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7643527204502815},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6402232191705876},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6014684538546913},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.569708870485785},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6709401709401709},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.632246998284734},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.5379454926624737},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.8305665349143609},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.8320668693009118},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6838775510204081},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.721041055718475},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6634358288770054},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.710007639419404},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7295645530939647},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6532212885154063},
]

anticommunism_v3 = [
{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.7105911, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.3905445, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.34281918, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.5081409, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.2752681, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 1.0387193, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.74365157, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'WEAT', 'score': 0.59058785, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 0.2233369, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': -0.024810374, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': -0.1723025, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.4504577, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.3248202, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.2087758, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.1594375, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'WEAT', 'score': 1.0621493, 'significance': False},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.57084304, 'significance': False},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.46363908, 'significance': False},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': -0.119513705, 'significance': False},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.253344, 'significance': False},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.3745935, 'significance': False},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.2442566, 'significance': False},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 0.964306, 'significance': False},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'WEAT', 'score': 1.2379115, 'significance': False},  

{'slice': 'KR1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.9082732355562758},
{'slice': 'KR2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.8871415356151712},
{'slice': 'Weimar', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.9229249011857708},
{'slice': 'CDU1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.672859025032938},
{'slice': 'SPD1', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7261451726568005},
{'slice': 'CDU2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.6898550724637681},
{'slice': 'SPD2', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.7553206483439041},
{'slice': 'CDU3', 'specification': 'anticommunism_sentiment', 'measure': 'ECT', 'score': 0.679309281529448},


{'slice': 'KR1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7833460656990069},
{'slice': 'KR2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.7427767354596624},
{'slice': 'Weimar', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6165882481671956},
{'slice': 'CDU1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6027490822163408},
{'slice': 'SPD1', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.5977973192179629},
{'slice': 'CDU2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6519916142557651},
{'slice': 'SPD2', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.6477225080998665},
{'slice': 'CDU3', 'specification': 'anticommunism_politics', 'measure': 'ECT', 'score': 0.48252334667429},


{'slice': 'KR1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.8325428194993413},
{'slice': 'KR2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.8526921406860616},
{'slice': 'Weimar', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6881632653061224},
{'slice': 'CDU1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7093108504398825},
{'slice': 'SPD1', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6410427807486632},
{'slice': 'CDU2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6895339954163482},
{'slice': 'SPD2', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.7170359052711993},
{'slice': 'CDU3', 'specification': 'anticommunism_propaganda', 'measure': 'ECT', 'score': 0.6876750700280113},
]

import seaborn as sns
from matplotlib import pyplot as plt
import pandas as pd
from google.colab import files
import numpy as np

def plot_bias_line(data, statistic, title):
  data_list = []
  for d in data:
    if d["measure"] == statistic:
       d["view"] = d["specification"].split("_")[2] if len(d["specification"].split("_")) > 2 else d["specification"].split("_")[1]
       data_list.append(d)
  # print(data_list)
  df = pd.DataFrame(data_list)
  sns.set_theme()

  g = sns.lineplot(data=df,
      x="slice", 
      y="score", 
      hue="view", 
      style="view", 
      alpha=.6, 
      palette="hls"
  )


  #g.despine(left=True)
  #g.set_axis_labels("", statistic)
  #g.legend.set_title("")

  plt.savefig(title + ".pdf")
  files.download(title + ".pdf")

def plot_all_lines(data, statistic, title):
  data_list = []
  for d in data:
    if d["measure"] == statistic:
       d["view"] = d["specification"].split("_")[2] if len(d["specification"].split("_")) > 2 else d["specification"].split("_")[1]
       data_list.append(d)
  df = pd.DataFrame(data_list)
  sns.set_theme()

  g = sns.lineplot(data=df,
      x="slice", 
      y="score", 
      hue="view", 
      style="view", 
      alpha=.6, 
      palette="hls"
  )


  #g.despine(left=True)
  #g.set_axis_labels("", statistic)
  #g.legend.set_title("")

  plt.savefig(title + ".pdf")
  files.download(title + ".pdf")

def plot_aggregated_line(data, statistic, title):
  data_list = []
  for d in data:
    if d["measure"] == statistic:
       d["view"] = d["specification"].split("_")[2] if len(d["specification"].split("_")) > 2 else d["specification"].split("_")[1]
       data_list.append(d)
  # print(data_list)
  df = pd.DataFrame(data_list)
  sns.set_theme()

  g = sns.lineplot(data=df,
      x="slice", 
      y="score", 
      # hue="view", 
      # style="view", 
      alpha=.6, 
      palette="hls"
  )


  #g.despine(left=True)
  #g.set_axis_labels("", statistic)
  #g.legend.set_title("")

  plt.savefig(title + ".pdf")
  files.download(title + ".pdf")



"""# Antisemitism - WEAT *Scores*"""

plot_bias_line(antisemitism_original, "WEAT", "antisemitism_original_WEAT")

plot_bias_line(antisemitism_recomputed, "WEAT", "antisemitism_recomputed_WEAT")

plot_bias_line(antisemitism_v1, "WEAT", "antisemitism_v1_WEAT")

plot_bias_line(antisemitism_v2, "WEAT", "antisemitism_v2_WEAT")

plot_bias_line(antisemitism_v3, "WEAT", "antisemitism_v3_WEAT")

"""# Anticommunism WEAT Scores"""

plot_bias_line(anticommunism_original, "WEAT", "anticommunism_original_WEAT")

plot_bias_line(anticommunism_recomputed, "WEAT", "anticommunism_recomputed_WEAT")

plot_bias_line(anticommunism_v1, "WEAT", "anticommunism_v1_WEAT")

plot_bias_line(anticommunism_v2, "WEAT", "anticommunism_v2_WEAT")

plot_bias_line(anticommunism_v3, "WEAT", "anticommunism_v3_WEAT")

"""# ECT DIAGRAMS"""

plot_bias_line(antisemitism_original, "ECT", "antisemitism_original_ECT")

plot_bias_line(antisemitism_recomputed, "ECT", "antisemitism_recomputed_ECT")

plot_bias_line(antisemitism_v1, "ECT", "antisemitism_v1_ECT")

plot_bias_line(antisemitism_v2, "ECT", "antisemitism_v2_ECT")

plot_bias_line(antisemitism_v3, "ECT", "antisemitism_v3_ECT")

plot_bias_line(anticommunism_original, "ECT", "anticommunism_original_ECT")

plot_bias_line(anticommunism_recomputed, "ECT", "anticommunism_recomputed_ECT")

plot_bias_line(anticommunism_v1, "ECT", "anticommunism_v1_ECT")

plot_bias_line(anticommunism_v2, "ECT", "anticommunism_v2_ECT")

plot_bias_line(anticommunism_v3, "ECT", "anticommunism_v3_ECT")